import type { Metadata } from "next";
import { Playfair_Display, Inter } from "next/font/google";
import "./globals.css";
import Footer from "./components/footer";


const inter = Inter({
  variable: "--font-inter",
  weight: [ "100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${playfairDisplay.variable} antialiased flex flex-col min-h-screen relative isolate`}
      >
        <div className="h-[35vw] w-[35vw] absolute top-0 left-0 -z-10 overflow-hidden">
          <div className="h-full w-full bg-dawn-orange rounded-full translate-x-[-50%] translate-y-[-50%] blur-3xl opacity-25"></div>
        </div>
        <header>Space for header</header>
        <div className="flex-1 px-4">
          {children}
        </div>
        <Footer/>
      </body>
    </html>
  );
}
